### ISSUE TITLE
Error in PupilDetector.py

### ISSUE THREAD

**Issue by rohanpillai20** [jonnedtc/PupilDetector#1]
I am getting the following error:

> def track(self, image, (py, px), sigma = 2, radius=50, distance = 10):
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
> SyntaxError: invalid syntax

**Comment by alisdt** [comment]
This is because tuple unpacking is not allowed in Python 3, use:
```
def track(self, image, prev, sigma = 2, radius=50, distance = 10):
    py, px = prev
```

**Comment by jonnedtc** [comment]
#4
